name: docmobi
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  intl: ^0.20.2
  image_picker: ^1.2.1

  # HTTP requests er jonno
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  
  # JSON serialization (optional but helpful)
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/patient.png
    - assets/images/doctor.png
    - assets/images/doctors.png
    - assets/images/map.png
    - assets/images/profile.png
    - assets/images/doctor_booking.png
    - assets/images/doctor1.png
    - assets/images/doctor2.png
    - assets/images/doctor3.png
    - assets/images/doctor4.png
    - assets/images/doctor5.png
    - assets/images/reelsviewdoctor.png
    - assets/images/news.png
    - assets/icons/